"""마크다운 리포트 생성 — 콘솔 출력 + reports/ 파일 저장."""
from __future__ import annotations

from ..config import Config
from ..domain import MacroSnapshot, PortfolioReview, StockVerdict
from .service import AnalysisResult

_ACTION_EMOJI = {
    "적극매수": "🟢🟢",
    "분할매수": "🟢",
    "관망": "⚪",
    "비중축소": "🟠",
    "매도": "🔴",
}
_JUDGE_EMOJI = {"저평가": "🟢", "적정": "⚪", "고평가": "🔴"}


def _money(v, cur: str) -> str:
    if v is None:
        return "N/A"
    sym = "₩" if cur == "KRW" else "$"
    if cur == "KRW":
        return f"{sym}{v:,.0f}"
    return f"{sym}{v:,.2f}"


def _pct_from(price, target) -> str:
    if not price or target is None:
        return ""
    return f"({(target/price-1)*100:+.1f}%)"


def build_markdown(result: AnalysisResult, cfg: Config, generated_at: str) -> str:
    engine_label = (
        "Claude API (전문가 에이전트 실시간 토론)"
        if result.engine_kind == "LLMEngine"
        else "규칙기반(오프라인) 엔진"
    )
    out: list[str] = []
    out.append("# 📊 주식 종목 분석 리포트")
    out.append("")
    out.append(f"- 생성 시각: {generated_at}")
    out.append(f"- 분석 엔진: {engine_label}")
    out.append(f"- 분석 종목 수: {len(result.verdicts)}")
    out.append("")
    out.append(
        "> ⚠️ **투자 유의**: 본 리포트는 참고용 분석이며 투자 권유가 아닙니다. "
        "최종 투자 판단과 책임은 투자자 본인에게 있습니다."
    )
    out.append("")

    # ---------------------------------------------------------- 추천 순위
    if result.ranking:
        out.append("## 🏆 추천 순위")
        out.append("")
        out.append("| 순위 | 종목 | 종합점수 | 대응 | 한줄평 |")
        out.append("|---:|---|---:|:--:|---|")
        for e in result.ranking:
            emoji = _ACTION_EMOJI.get(e.action, "")
            out.append(
                f"| {e.rank} | {e.ticker.display()} | {e.total_score:.0f} | "
                f"{emoji} {e.action} | {e.one_liner} |"
            )
        out.append("")
        if result.ranking_summary:
            out.append(f"**총평:** {result.ranking_summary}")
            out.append("")

    # ---------------------------------------------------------- 종목별 상세
    for v in result.verdicts:
        out.extend(_verdict_section(v, cfg))

    # ---------------------------------------------------------- 거시 부록
    out.append("## 🌐 시장 국면(거시) 요약")
    out.append("")
    for mkt, snap in result.macro.items():
        op = result.macro_opinions.get(mkt)
        out.append(f"### {mkt} 시장")
        if op:
            out.append(f"- 국면 입장: **{op.stance}** (주식비중 매력도 {op.score:.0f}/100)")
            out.append(f"- {op.summary}")
        out.extend(_macro_indicator_lines(snap))
        out.append("")

    if result.errors:
        out.append("## ⚠️ 처리 중 오류")
        out.append("")
        for err in result.errors:
            out.append(f"- {err}")
        out.append("")

    out.append("---")
    out.append("*Generated by StockAdvisor — 멀티 에이전트 분석 프로그램.*")
    return "\n".join(out)


def _verdict_section(v: StockVerdict, cfg: Config) -> list[str]:
    cur = v.currency
    je = _JUDGE_EMOJI.get(v.valuation_judgment, "")
    ae = _ACTION_EMOJI.get(v.action, "")
    o: list[str] = []
    o.append(f"## {v.ticker.display()}")
    o.append("")
    o.append(f"- 현재가: **{_money(v.current_price, cur)}**")
    o.append(f"- 주가 적정성: {je} **{v.valuation_judgment}**")
    o.append(f"- 현재 대응: {ae} **{v.action}** (확신도 {v.conviction:.0f}/100, 종합 {v.total_score:.0f})")
    if v.suggested_position_pct is not None:
        o.append(f"- 권고 비중 상한: **{v.suggested_position_pct:.0f}%**")
    if v.stop_loss is not None:
        o.append(f"- 손절 권고가: **{_money(v.stop_loss, cur)}** {_pct_from(v.current_price, v.stop_loss)}")
    o.append("")
    if v.thesis:
        o.append(f"**투자 논리:** {v.thesis}")
        o.append("")

    # 기간별 목표가 테이블
    o.append("### 🎯 투자 기간별 목표가")
    o.append("")
    o.append("| 기간 | 보수적 | 기준 | 낙관적 | 근거 |")
    o.append("|---|---:|---:|---:|---|")
    for b in v.target_prices.bands():
        base_pct = _pct_from(v.current_price, b.base)
        o.append(
            f"| {b.horizon} | {_money(b.low, cur)} | **{_money(b.base, cur)}** {base_pct} "
            f"| {_money(b.high, cur)} | {b.rationale} |"
        )
    o.append("")

    if v.key_risks:
        o.append("**주요 리스크:**")
        o.extend(f"- {r}" for r in v.key_risks)
        o.append("")
    if v.catalysts:
        o.append("**상승 촉매:**")
        o.extend(f"- {c}" for c in v.catalysts)
        o.append("")

    # 전문가별 의견
    o.append("### 🧠 전문가 의견")
    o.append("")
    o.append("| 전문가 | 입장 | 점수 | 확신 | 요약 |")
    o.append("|---|:--:|---:|---:|---|")
    for op in v.opinions:
        o.append(
            f"| {op.role} | {op.stance} | {op.score:.0f} | {op.confidence:.2f} | {op.summary} |"
        )
    o.append("")
    # 핵심 포인트/리스크 상세
    for op in v.opinions:
        if op.key_points or op.risks:
            o.append(f"<details><summary>{op.role} 상세</summary>")
            o.append("")
            if op.key_points:
                o.append("- 핵심 포인트:")
                o.extend(f"  - {p}" for p in op.key_points)
            if op.risks:
                o.append("- 리스크:")
                o.extend(f"  - {r}" for r in op.risks)
            o.append("")
            o.append("</details>")
            o.append("")
    o.append("---")
    o.append("")
    return o


def _macro_indicator_lines(snap: MacroSnapshot) -> list[str]:
    lines = []
    for k, val in snap.indicators.items():
        if isinstance(val, dict):
            lvl = val.get("level")
            chg = val.get("change_3m_pct")
            chg_s = f", 3M {chg:+.1f}%" if isinstance(chg, (int, float)) else ""
            lines.append(f"  - {k}: {lvl}{chg_s}")
    return lines


_POS_ACTION_EMOJI = {
    "추가매수": "🟢",
    "보유": "⚪",
    "일부익절": "🔵",
    "비중축소": "🟠",
    "손절": "🔴",
}


def _base_money(v: float, cur: str) -> str:
    sym = "₩" if cur == "KRW" else "$"
    return f"{sym}{v:,.0f}" if cur == "KRW" else f"{sym}{v:,.2f}"


def build_portfolio_markdown(
    review: PortfolioReview, cfg: Config, generated_at: str, engine_kind: str
) -> str:
    engine_label = (
        "Claude API (리스크 매니저 정성 점검)"
        if engine_kind == "LLMEngine"
        else "규칙기반(오프라인) 엔진"
    )
    bc = review.base_currency
    pnl_emoji = "🔴" if review.total_pnl_base < 0 else "🟢"
    o: list[str] = []
    o.append("# 💼 보유 포트폴리오 모니터링 리포트")
    o.append("")
    o.append(f"- 생성 시각: {generated_at}")
    o.append(f"- 점검 엔진: {engine_label}")
    o.append(f"- 기준통화: {bc} (USD/KRW {review.fx_usdkrw:,.1f})")
    o.append("")
    o.append("## 📈 포트폴리오 요약")
    o.append("")
    o.append(f"- 총 평가금액: **{_base_money(review.total_value_base, bc)}**")
    o.append(f"- 총 매입금액: {_base_money(review.total_cost_base, bc)}")
    o.append(
        f"- 총 평가손익: {pnl_emoji} **{_base_money(review.total_pnl_base, bc)} "
        f"({review.total_pnl_pct:+.1f}%)**"
    )
    if review.cash_base:
        o.append(f"- 현금: {_base_money(review.cash_base, bc)}")
    o.append("")

    # 비중
    if review.market_weights:
        o.append("**시장 비중:** " + ", ".join(f"{k} {v:.0f}%" for k, v in review.market_weights.items()))
    if review.sector_weights:
        o.append("**섹터 비중:** " + ", ".join(f"{k} {v:.0f}%" for k, v in review.sector_weights.items()))
    o.append("")

    # 종목 테이블
    o.append("## 📋 보유 종목별 점검")
    o.append("")
    o.append("| 종목 | 수익률 | 비중 | 평가금액 | 조치 | 손절가 | 코멘트 |")
    o.append("|---|---:|---:|---:|:--:|---:|---|")
    for p in review.positions:
        emoji = _POS_ACTION_EMOJI.get(p.action, "")
        pnl_s = f"{p.pnl_pct:+.1f}%"
        cur = p.currency
        mv = _money(p.market_value, cur)
        sl = _money(p.stop_loss, cur) if p.stop_loss is not None else "-"
        o.append(
            f"| {p.ticker.display()} | {pnl_s} | {p.weight_pct:.1f}% | {mv} | "
            f"{emoji} {p.action} | {sl} | {p.comment} |"
        )
    o.append("")

    if review.risk_alerts:
        o.append("## ⚠️ 리스크 경고")
        o.append("")
        o.extend(f"- {a}" for a in review.risk_alerts)
        o.append("")
    if review.rebalancing:
        o.append("## ⚖️ 리밸런싱 제안")
        o.append("")
        o.extend(f"- {r}" for r in review.rebalancing)
        o.append("")
    if review.summary:
        o.append("## 🧠 종합 코멘트")
        o.append("")
        o.append(review.summary)
        o.append("")
    if review.errors:
        o.append("## 🛑 처리 오류")
        o.append("")
        o.extend(f"- {e}" for e in review.errors)
        o.append("")

    o.append("---")
    o.append(
        "> ⚠️ 참고용 모니터링이며 투자 권유가 아닙니다. 최종 판단·책임은 투자자 본인에게 있습니다."
    )
    o.append("*Generated by StockAdvisor — 보유 종목 모니터링.*")
    return "\n".join(o)


def write_report(markdown: str, cfg: Config, filename: str) -> str:
    path = cfg.report_path / filename
    path.write_text(markdown, encoding="utf-8")
    return str(path)
